import React,{useState}from'react';import{Menu,X,Search,UploadCloud,Inbox,ChevronUp,ChevronDown,Loader2}from'lucide-react';
export const cn=(...v)=>v.filter(Boolean).join(' ');
export function Button({children,variant='primary',className='',...p}){let v={primary:'bg-[#335cff] text-white hover:bg-[#254be4] shadow-[0_1px_2px_rgba(15,23,42,.16),0_6px_16px_rgba(51,92,255,.18)]',secondary:'bg-white text-slate-700 border border-slate-200 hover:border-slate-300 hover:bg-slate-50 shadow-[0_1px_2px_rgba(15,23,42,.04)]',ghost:'text-slate-600 hover:bg-slate-100',danger:'bg-red-600 text-white hover:bg-red-700'}[variant];return <button className={cn('inline-flex h-10 items-center justify-center gap-2 rounded-[10px] px-4 text-[13px] font-semibold tracking-[-.01em] transition-all duration-200 disabled:pointer-events-none disabled:opacity-50 active:translate-y-px',v,className)} {...p}>{children}</button>}
export function Card({children,className=''}){return <div className={cn('rounded-[18px] border border-slate-200/80 bg-white shadow-[0_1px_2px_rgba(15,23,42,.025),0_8px_24px_rgba(15,23,42,.035)]',className)}>{children}</div>}
export function Badge({children,tone='neutral'}){let t={success:'bg-emerald-50 text-emerald-700 ring-emerald-600/15',warning:'bg-orange-50 text-orange-700 ring-orange-600/15',danger:'bg-red-50 text-red-700 ring-red-600/15',info:'bg-blue-50 text-blue-700 ring-blue-600/15',neutral:'bg-slate-100 text-slate-600 ring-slate-500/10'}[tone];return <span className={cn('inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-xs font-semibold ring-1 ring-inset',t)}>{children}</span>}
export const scoreTone=s=>s>=85?'success':s>=70?'warning':'danger';
export function ProgressBar({value,color='bg-brand'}){return <div className="h-1.5 overflow-hidden rounded-full bg-slate-100 ring-1 ring-inset ring-slate-200/60"><div className={cn('h-full rounded-full transition-all duration-700',color)} style={{width:`${value}%`}}/></div>}
export function SearchBar({value,onChange,placeholder='Search candidates...'}){return <label className="relative block"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={value} onChange={e=>onChange?.(e.target.value)} placeholder={placeholder} className="w-full rounded-xl border border-slate-200 bg-white py-2.5 pl-10 pr-4 text-sm outline-none focus:border-brand focus:ring-4 focus:ring-blue-100"/></label>}
export function EmptyState({title='Nothing here yet',text='Your data will appear here.',action}){return <div className="py-16 text-center"><div className="mx-auto mb-4 grid h-12 w-12 place-items-center rounded-2xl bg-slate-100"><Inbox className="h-5 w-5 text-slate-500"/></div><h3 className="font-semibold text-slate-900">{title}</h3><p className="mx-auto mt-1 max-w-sm text-sm text-slate-500">{text}</p>{action&&<div className="mt-5">{action}</div>}</div>}
export function LoadingSkeleton(){return <div className="animate-pulse space-y-4"><div className="h-8 w-48 rounded bg-slate-200"/><div className="grid gap-4 md:grid-cols-3">{[1,2,3].map(x=><div key={x} className="h-28 rounded-2xl bg-slate-100"/>)}</div><div className="h-64 rounded-2xl bg-slate-100"/></div>}
export function ErrorState({retry}){return <EmptyState title="We couldn't load this data" text="Check your connection and try again." action={<Button onClick={retry}>Try again</Button>}/>}
export function Modal({open,onClose,title,children}){if(!open)return null;return <div className="fixed inset-0 z-50 grid items-end bg-slate-950/40 p-0 backdrop-blur-sm md:place-items-center md:p-6" onMouseDown={onClose}><Card className="w-full max-w-xl rounded-b-none p-6 md:rounded-2xl" onMouseDown={e=>e.stopPropagation()}><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-bold">{title}</h2><button onClick={onClose}><X/></button></div>{children}</Card></div>}
export function Tabs({items,active,onChange}){return <div className="flex gap-1 rounded-xl bg-slate-100 p-1">{items.map(i=><button key={i} onClick={()=>onChange(i)} className={cn('flex-1 rounded-lg px-3 py-2 text-sm font-medium transition',active===i?'bg-white text-slate-900 shadow-sm':'text-slate-500')}>{i}</button>)}</div>}
export function FileUpload({onFile}){let[drag,setDrag]=useState(false);return <label onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);onFile?.(e.dataTransfer.files[0])}} className={cn('block cursor-pointer rounded-2xl border-2 border-dashed p-10 text-center transition',drag?'border-brand bg-blue-50':'border-slate-200 hover:border-blue-300 hover:bg-slate-50')}><UploadCloud className="mx-auto h-8 w-8 text-brand"/><p className="mt-3 font-semibold">Drop your resume here</p><p className="mt-1 text-sm text-slate-500">PDF or DOCX, up to 5 MB</p><input type="file" className="hidden" accept=".pdf,.doc,.docx" onChange={e=>onFile?.(e.target.files[0])}/></label>}
export function DataTable({columns,rows,onRow}){return <><div className="hidden overflow-hidden rounded-[18px] border border-slate-200/90 bg-white shadow-[0_1px_2px_rgba(15,23,42,.02)] md:block"><table className="w-full text-left"><thead className="border-b border-slate-200 bg-[#fafbfc] text-[10px] uppercase tracking-[.12em] text-slate-500"><tr>{columns.map(c=><th key={c.key} className="px-5 py-3.5 font-bold">{c.label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map((r,i)=><tr key={r.id||i} onClick={()=>onRow?.(r)} className="group cursor-pointer transition-colors hover:bg-[#f7f9ff]">{columns.map(c=><td key={c.key} className="px-5 py-[17px] text-[13px] text-slate-700 first:text-slate-950">{c.render?c.render(r):r[c.key]}</td>)}</tr>)}</tbody></table></div><div className="grid gap-3 md:hidden">{rows.map((r,i)=><Card key={r.id||i} className="cursor-pointer p-4" onClick={()=>onRow?.(r)}>{columns.map(c=><div key={c.key} className="flex items-center justify-between gap-4 py-1.5"><span className="text-xs font-medium text-slate-500">{c.label}</span><span className="text-right text-sm">{c.render?c.render(r):r[c.key]}</span></div>)}</Card>)}</div></>}

